name: bubaleh

on:
  push:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USER_NAME }}/my-flask-app:v1.0.${{ github.run_number }}
            ${{ secrets.DOCKER_USER_NAME }}/my-flask-app:latest
          context: DevOps

      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: project/
          key: ${{secrets.SSH_PRIVATE_KEY_EC2}}
          inventory: |
            [ec2_hosts]
            ${{secrets.REMOTE_HOST_IP}} ansible_ssh_user=${{secrets.EC2_USER_NAME}}
          options: |
            --verbose